services:
  # ai-engine:
  #   build:
  #     context: ./ai-engine
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./ai-engine:/app
  #     - pip-cache:/root/.cache/pip
  #   environment:
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - GEMINI_API_KEY=${GEMINI_API_KEY}
  #     - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
  #     - COQUI_TOS_AGREED=1
  #   ports:
  #     - "5000:5000"
  #   devices:
  #     - /dev/nvidia0:/dev/nvidia0
  #     - /dev/nvidiactl:/dev/nvidiactl
  #     - /dev/nvidia-uvm:/dev/nvidia-uvm

  game-server:
    build:
      context: ./game-server
      dockerfile: Dockerfile
    volumes:
      - ./game-server:/app
      - /app/node_modules
      - ./d-ai-rpg-firebase-adminsdk.json:/app/config/d-ai-rpg-firebase-adminsdk.json
    command: sh -c "npm install --no-audit --no-fund && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/rpg_game
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_AUDIO_BUCKET_NAME=audio-files
      - MINIO_IMAGE_BUCKET_NAME=image-files
      - JWT_SECRET=ai-dungeonmaster-secret
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/d-ai-rpg-firebase-adminsdk.json
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_REFERER=${OPENROUTER_REFERER}
    depends_on:
      # - ai-engine
      - mongodb      
      - minio

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install --no-audit --no-fund && npm start"
    ports:
      - "80:3000"
      - "443:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - PUBLIC_URL=${PUBLIC_URL}
      - API_URL=${API_URL}
    depends_on:
      - game-server

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflare-config.yml:/etc/cloudflared/config.yml:ro
      - ./cloudflare-tunnel-credentials.json:/etc/cloudflared/credentials.json:ro
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - game-server
      - frontend
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  mongodb:
    image: mongo:4.4.18
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  pip-cache:
    driver: local
  mongodb_data:
  minio_data:

networks:
  default:
    name: ai-dungeonmaster-network