version: '3.8'

services:
  ai-engine:
    build:
      context: ./ai-engine
      dockerfile: Dockerfile
    volumes:
      - ./ai-engine:/app
      - pip-cache:/root/.cache/pip
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5000:5000"

  game-server:
    build:
      context: ./game-server
      dockerfile: Dockerfile
    volumes:
      - ./game-server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/rpg_game
    depends_on:
      - ai-engine
      - mongodb      

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "80:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - game-server

  mongodb:
    image: mongo:4.4.18
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  pip-cache:
    driver: local
  mongodb_data:

networks:
  default:
    name: ai-dungeonmaster-network